# Generated by Django 2.2.2 on 2019-06-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_auto_20190626_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.EmailField(max_length=254),
        ),
    ]
